[package]
name = "cvmodtool"
version = "0.3.0"
authors = ["Csányi István <icsanyi96@gmail.com>"]
edition = "2018"
description = "Code Vein modding helper tool for managing UE4 projects"
readme = "README.md"
repository = "https://github.com/AmionSky/cvmodtool"
license = "GPL-3.0-only"
publish = false

[workspace]
members = [
    "updater",
]

[dependencies]
clap = "3.0.0-beta.1"
serde = { version = "1.0", features = ["derive"] }
json = { package = "serde_json", version = "1.0" }
toml = "0.5"
walkdir = "2.3"
colour = "0.5"
updater = { path = "updater" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false