[package]
name = "cvmodtool"
version = "0.1.0"
authors = ["Csányi István <icsanyi96@gmail.com>"]
edition = "2018"

[dependencies]
clap = "^3.0.0-beta.1"
serde = { version = "1.0", features = ["derive"] }
json = { package = "serde_json", version = "1.0" }
toml = "0.5"
walkdir = "2.3"
colour = "0.5.0"