[package]
name = "cvmodtool"
version = "0.4.2"
authors = ["Amion <icsanyi96@gmail.com>"]
edition = "2021"
description = "Code Vein modding helper tool for managing UE4 projects"
readme = "README.md"
repository = "https://github.com/AmionSky/cvmodtool"
license = "GPL-3.0-only"
publish = false

[dependencies]
clap = { version = "3.0", features = ["derive", "unicode"] }
serde = { version = "1.0", features = ["derive"] }
json = { package = "serde_json", version = "1.0" }
toml = "0.7"
walkdir = "2.3"
colour = "0.7"

[dependencies.updater]
git = "https://github.com/AmionSky/updater"
rev = "470a6e4c7a2d67bb7bf3735e106f41a18c24e648"
features = ["procedures", "ext-zip"]
optional = true

[features]
default = ["updater"]

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"
