[package]
name = "cvmodtool"
version = "0.3.2"
authors = ["Csányi István <icsanyi96@gmail.com>"]
edition = "2021"
description = "Code Vein modding helper tool for managing UE4 projects"
readme = "README.md"
repository = "https://github.com/AmionSky/cvmodtool"
license = "GPL-3.0-only"
publish = false

[dependencies]
clap = { version = "3.0", features = ["derive", "unicode"] }
serde = { version = "1.0", features = ["derive"] }
json = { package = "serde_json", version = "1.0" }
toml = "0.5"
walkdir = "2.3"
colour = "0.6"

[dependencies.updater]
git = "https://github.com/AmionSky/updater"
rev = "300cf600ba4db07ad5504451b8abbcece2b57cf7"
features = ["procedures", "ext-zip"]
optional = true

[features]
default = ["updater"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
