full = [
    'base',
    'extensions',
    'gitsupport',
    'enemies',
    'spawner',
    'interactive',
    'stateful',
    'startmap',
    'workmapdoor',
    'ladder',
    'killvolume',
]
default = [
    'base',
    'extensions',
    'enemies',
    'spawner',
    'interactive',
    'stateful',
    'startmap',
    'workmapdoor',
    'ladder',
    'killvolume',
]
min = ['base']
empty = []
nocompile = ['base', 'enemies', 'spawner', 'startmap', 'killvolume']
