full = ['base', 'extensions', 'gitsupport', 'enemies', 'spawner', 'interactive', 'stateful', 'startmap', 'workmapdoor', 'ladder']
default = ['base', 'extensions', 'enemies', 'spawner', 'interactive', 'stateful', 'startmap', 'workmapdoor', 'ladder']
min = ['base']
empty = []

nocompile = ['base', 'enemies', 'spawner', 'startmap']
