name: New Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build Executable
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update --no-self-update stable
      - name: Install targets
        run: rustup target install x86_64-pc-windows-msvc
      - name: Build
        run: cargo build --target x86_64-pc-windows-msvc --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: target/x86_64-pc-windows-msvc/release/cvmodtool.exe
          if-no-files-found: error

  zip:
    name: Zip Resources
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Zip
        run: sudo apt-get install zip
      - name: Zip files
        run: cd resources && zip -r -9 ../resources.zip ./*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resources
          path: resources.zip
          if-no-files-found: error

  create:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, zip]
    timeout-minutes: 5
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Code Vein Modding Tool ${{ github.ref_name }}
          files: |
            executable/cvmodtool.exe
            resources/resources.zip
